### ISSUE TITLE
Bug: Wrong module prefix in query

### ISSUE THREAD

**Issue by taylorr4** [vanderbilt-redcap/email-alerts-module#14]
Shouldn't this query reference the prefix "email_alerts" instead of "vanderbilt_emailTrigger", which is the module's name only on the Vanderbilt server? If this is the case, I can't imagine that the cron job has ever worked for anyone outside of Vanderbilt who downloaded this from the REDCap Repo.

https://github.com/vanderbilt-redcap/email-alerts-module/blob/94792f2b0c3467a172fa6c146c0dcd4ba63574f4/EmailTriggerExternalModule.php#L326

**Comment by knil-maloon** [comment]
Thanks for finding this!
I added an OR to the sql
