### ISSUE TITLE
file attachment does not work if using S3 as file storage method

### ISSUE THREAD

**Issue by targetpharma** [vanderbilt-redcap/email-alerts-module#15]
The add attachment functionality assumes local server file storage option even if configured to use S3.

In EmailTriggerExternalModule.php, the code assumes the use of EDOC_PATH for file retrieval.

```php
    /**
     * Function that adds a new attachment (file or image type) to the mail if the file exists in the DB and if it's no bigger than 3MB to send. Otherwise it sends an error email
     * @param $mail
     * @param $edoc
     * @param $project_id
     * @return mixed
     */
    function addNewAttachment($mail,$edoc,$project_id, $type){
...
                    if($type == 'files'){
                        //attach file with a different name
                        $mail->AddAttachment(EDOC_PATH . $row['stored_name'], $row['doc_name']);
                    }else if($type == 'images'){
                        $mail->AddEmbeddedImage(EDOC_PATH . $row['stored_name'],$edoc);
                    }
```

**Comment by knil-maloon** [comment]
This would be a great addition.  Unfortunately we cannot justify working on this for the project that currently funds support for this module.  If you want to create a pull request, I'll try to review and merge it soon.

**Comment by targetpharma** [comment]
Thanks for the quick response and feedback.

I'll see what we have time to do on our end. For now, I resorted to providing a link in the email back to the data form which would  let the recipient quickly load the data form and download any files that way.

Great module BTW!
