### ISSUE TITLE
Preview Message by Record functionality not working in v2.1.5 (does work in v2.1.4)

### ISSUE THREAD

**Issue by targetpharma** [vanderbilt-redcap/email-alerts-module#16]
Using REDCap 8.10.6.

![image](https://user-images.githubusercontent.com/20141935/54763217-f5746100-4bcb-11e9-9405-844187fa7bd5.png)

This same Preview Message by Record is working in v2.1.4. Between the two versions, phpmailer appears to have been upgraded / moved to a newer version:

```
$ cat email_alerts_v2.1.4/vendor/phpmailer/phpmailer/VERSION 
5.2.23

$ cat email_alerts_v2.1.5/vendor/phpmailer/phpmailer/VERSION 
6.0.7
```

**Comment by knil-maloon** [comment]
Hi @targetpharma 
Indeed we upgraded the phpMailer version. The Form preview didn't get this update so I just submitted a new version with a fix for it that will be soon available.
