### ISSUE TITLE
v2.2.2 Error

### ISSUE THREAD

**Issue by jasonlones** [vanderbilt-redcap/email-alerts-module#18]
The 'hook_save_record' hook did not complete for the 'email_alerts' module because of the following error:

Error Message: Uncaught Error: Cannot use assign-op operators with string offsets in /var/www/html/redcap/modules/email_alerts_v2.2.2/EmailTriggerExternalModule.php:611
Stack trace:
#0 /var/www/html/redcap/modules/email_alerts_v2.2.2/EmailTriggerExternalModule.php(208): Vanderbilt\EmailTriggerExternalModule\EmailTriggerExternalModule->getProjectSettingLog('196', 'email-records-s...')
#1 /var/www/html/redcap/modules/email_alerts_v2.2.2/EmailTriggerExternalModule.php(95): Vanderbilt\EmailTriggerExternalModule\EmailTriggerExternalModule->sendEmailAlert('196', 2, Array, 12, '336', 'demographics', 1, false)
#2 /var/www/html/redcap/modules/email_alerts_v2.2.2/EmailTriggerExternalModule.php(75): Vanderbilt\EmailTriggerExternalModule\EmailTriggerExternalModule->sendEmailFromSurveyCode('HNHH7KPMPR', '196', 2, Array, 12, '336', 'demographics', 1, false, 'demographics')
#3 [internal function]: Vanderbilt\EmailTriggerExternalModule\EmailTriggerExternalModule->hook_save_record('196', 12, 'demographics', '336', NULL, 'HNHH7KPMPR', 1484, 
File: /var/www/html/redcap/modules/email_alerts_v2.2.2/EmailTriggerExternalModule.php
Line: 611

**Comment by knil-maloon** [comment]
Hi @jasonlones 

We were fixing some bugs and I checked on this error. I'm not sure why it's giving you an error but it's an easy change so I will add it in the next downloadable which should be available soon.
