### ISSUE TITLE
Resend Emails on Form Re-save Javascript Form Validation Fails

### ISSUE THREAD

**Issue by velezf** [vanderbilt-redcap/email-alerts-module#20]
When the Resend Emails on Form Re-save box is not checked I get the error "undefined is not a valid number for number of days". 
The number of days field is not displaying

redcap v 9.1.5 
plugin version 2.2.3

**Comment by knil-maloon** [comment]
Hi Velezf,
Only users with user "User Rights" privileges can see that section. If you activate those you will be able to see that field.
For more information, this issue has been commented before on the community.
