### ISSUE TITLE
Fatal errors 

### ISSUE THREAD

**Issue by denshade** [vanderbilt-redcap/email-alerts-module#22]
Hi, 
we are getting the following fatal error in the latest version of the email-alerts-module: 

 PHP Fatal error:  Uncaught Exception: For security reasons, the 'record' parameter cannot be overridden via AJAX log requests.  It can be overridden only be overridden by PHP log requests.  You can add your own PHP page to this module to perform the logging, and call it via AJAX. in /var/www/html/epro/redcap_v9.5.8/ExternalModules/classes/AbstractExternalModule.php:1456\nStack trace:\n#0 /var/www/html/epro/redcap_v9.5.8/ExternalModules/manager/ajax/log.php(13): ExternalModules\\AbstractExternalModule->logAjax(Array)\n#1 {main}\n  thrown in /var/www/html/epro/redcap_v9.5.8/ExternalModules/classes/AbstractExternalModule.php on line 1456, referer: https://openredcap.uzgent.be/redcap_v9.5.8/DataEntry/index.php?pid=<masked>&page=start_new_redcap_project&id=112&event_id=608

Any ideas?

**Comment by mmcev106** [comment]
@denshade, do you have any other modules enabled on this project?

**Comment by mmcev106** [comment]
I asked about other modules because the Email Alerts Module doesn't do anything with the logging API that's throwing the error.  I just took a second look at the referer url, and I'm not sure I understand it?  What page is that?  It's not the normal create or copy project pages.  I'm not seeing the "start_new_redcap_project" string in any REDCap, module framework, or module source code.  I think we might need more information.

**Comment by denshade** [comment]
start_new_redcap_project is the name of the REDCap project. Tomorrow I'll have a look if any other modules are enabled.

**Comment by mmcev106** [comment]
It is normal for the `pid` to be blank in whatever scenario that URL was generated?

**Comment by denshade** [comment]
I've masked it. So in reality it's not empty.

**Comment by steentje34** [comment]
Upon further investigation, it seems that this issue is related to the combination of the Email Alerts EM & the Save Survey PDF to Field EM.

**Comment by denshade** [comment]
Closing issue as it is unrelated to the module.
