### ISSUE TITLE
Email Alert v2.3.5 crashes on RedCap 9.5.14

### ISSUE THREAD

**Issue by u0046038** [vanderbilt-redcap/email-alerts-module#24]
REDCap crashed due to an unexpected PHP fatal error!

Error message: Uncaught Exception: An error occurred while running an External Module query. Query execution failed (see the server error log for more details). in /www/virtualhosts/redcap.gbiomed.kuleuven.be/html/redcap_v9.5.14/ExternalModules/classes/ExternalModules.php:2156 Stack trace: #0 /www/virtualhosts/redcap.gbiomed.kuleuven.be/html/redcap_v9.5.14/ExternalModules/classes/AbstractExternalModule.php(846): ExternalModules\ExternalModules::query('SELECT DISTINCT...') #1 /www/virtualhosts/redcap.gbiomed.kuleuven.be/html/modules/email_alerts_v2.3.5/EmailTriggerExternalModule.php(1693): ExternalModules\AbstractExternalModule->query('SELECT DISTINCT...', Array) #2 /www/virtualhosts/redcap.gbiomed.kuleuven.be/html/modules/email_alerts_v2.3.5/configure.php(27): Vanderbilt\EmailTriggerExternalModule\EmailTriggerExternalModule->getAdditionalFieldChoices(Array, '430') #3 /www/virtualhosts/redcap.gbiomed.kuleuven.be/html/redcap_v9.5.14/ExternalModules/index.php(102): require_once('/www/virtualhos...') #4 {main} thrown
File: /www/virtualhosts/redcap.gbiomed.kuleuven.be/html/redcap_v9.5.14/ExternalModules/classes/ExternalModules.php
Line: 2156

Logs says :

[11-May-2020 17:32:58 Europe/Brussels] An error occurred while running an External Module query: {
    "Message": "Query execution failed",
    "SQL": "SELECT DISTINCT form_name\n\t\t\t\t\tFROM redcap_metadata\n\t\t\t\t\tWHERE project_id = ?\n\t\t\t\t\tORDER BY field_order",
    "DB Error": "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?\n\t\t\t\t\tORDER BY field_order' at line 3",
    "Code": 0,
    "File": "\/www\/virtualhosts\/redcap.gbiomed.kuleuven.be\/html\/redcap_v9.5.14\/ExternalModules\/classes\/ExternalModules.php",
    "Line": 2135,
    "Trace": [
        {
            "file": "\/www\/virtualhosts\/redcap.gbiomed.kuleuven.be\/html\/redcap_v9.5.14\/ExternalModules\/classes\/AbstractExternalModule.php",
            "line": 846,
            "function": "query",
            "class": "ExternalModules\\ExternalModules",
            "type": "::",
            "args": [
                "SELECT DISTINCT form_name\n\t\t\t\t\tFROM redcap_metadata\n\t\t\t\t\tWHERE project_id = ?\n\t\t\t\t\tORDER BY field_order"
            ]
        },
...

**Comment by knil-maloon** [comment]
Hi @u0046038 

There was an issue where the redcap min version was incorrect in the last updates. I've removed those versions from the repo and updated the new one with the correct redcap min, version 9.7.8.

Also new Redcap LTS version will be released next month.

**Comment by u0046038** [comment]
Hi Eva,

We are using your email alert module in some very important COVID-19 studies…
Can we get this module working again asap in the LTS version we are working with ?

It’s so important to get this fixed…

Thank you for the fast response….

Kind Regards,

Gert Goos
Head of IT
Group Biomedical Sciences
University KU Leuven
Belgium

**Comment by knil-maloon** [comment]
Hi @u0046038 

You should be able to still use the module, it's just going to be an older version. We only changed some vulnerabilities and dependencies in the new ones but the functionality should be the same in older versions.

**Comment by u0046038** [comment]
Hi Eva,

When we click on ‘Configue Email Alerts’ we are receiving this message :

REDCap crashed due to an unexpected PHP fatal error!

Error message: Uncaught Exception: An error occurred while running an External Module query. Query execution failed (see the server error log for more details). in /www/virtualhosts/redcap.gbiomed.kuleuven.be/html/redcap_v9.5.14/ExternalModules/classes/ExternalModules.php:2156 Stack trace: #0 /www/virtualhosts/redcap.gbiomed.kuleuven.be/html/redcap_v9.5.14/ExternalModules/classes/AbstractExternalModule.php(846): ExternalModules\ExternalModules::query('SELECT DISTINCT...') #1 /www/virtualhosts/redcap.gbiomed.kuleuven.be/html/modules/email_alerts_v2.3.5/EmailTriggerExternalModule.php(1693): ExternalModules\AbstractExternalModule->query('SELECT DISTINCT...', Array) #2 /www/virtualhosts/redcap.gbiomed.kuleuven.be/html/modules/email_alerts_v2.3.5/configure.php(27): Vanderbilt\EmailTriggerExternalModule\EmailTriggerExternalModule->getAdditionalFieldChoices(Array, '130') #3 /www/virtualhosts/redcap.gbiomed.kuleuven.be/html/redcap_v9.5.14/ExternalModules/index.php(102): require_once('/www/virtualhos...') #4 {main} thrown
File:/www/virtualhosts/redcap.gbiomed.kuleuven.be/html/redcap_v9.5.14/ExternalModules/classes/ExternalModules.php
Line: 2156


Kind Regards,

Gert Goos

**Comment by knil-maloon** [comment]
Hi Gert,

You should first go in REDCap->Control Center->External Modules->Enable a Module + 
and search Email Alerts. You can change the version in there. I think version 2.3.2 or lower should be fine as that error seems still to be from the new version which is not compatible with your REDCap version.

Let me know how it goes.

Best,
Eva.

**Comment by u0046038** [comment]
Hi Eva,

So, many thanks !

It’s working again…

Didn’t know that i could lower the version of an module this way….

So many thanks !

Kind Regards,

Gert

**Comment by knil-maloon** [comment]
Woohoo!

You can do that with any external module. Now you know how :)
Glad I could help!
