### ISSUE TITLE
Settings not saving?

### ISSUE THREAD

**Issue by jwppch** [vanderbilt-redcap/email-alerts-module#3]
Hello-- trying out the Email Alerts 1.2 plugin and it seems like no matter what I add in the config fields (Email Addresses, Email Content, Email Errors), when I hit "Save Settings," nothing appears to happen.  If I navigate away and come back, anything I added is gone.  I've read the docs.  Anyway, I might be missing something.  Help/feedback would be great.

**Comment by jwppch** [comment]
Never mind... looks like it's IE.  Works just great in Chrome.  For some reason IE is not allowing whatever js action is taking place to commit.

**Comment by knil-maloon** [comment]
Thanks for the information. Glad you could make it work. I will try to dig on IE to see if there's a solution for this.
