### ISSUE TITLE
email_to disappears after editing a new email alert

### ISSUE THREAD

**Issue by dr01d3r** [vanderbilt-redcap/email-alerts-module#4]
Version: **Email Alerts - v1.3.2**
Browser: **Chrome Version 64.0.3282.186 (Official Build) (64-bit)**

Steps to reproduce:

1. Create an email alert with minimum required fields and a specified **Email To:**
   - Specified email shows up in the **Email Addresses** column
2. Click **Edit** for that entry
   - The modal does not bring forward the **Email To:** value that exists.
3. Re-enter the email address and click **Save**
   - The email does not save and does not show up in the **Email Addresses** column

As far as I know, there are no other hooks/EMs being executed against this project that could impact the update.

This error occurs with and without any module options specified.

**Comment by knil-maloon** [comment]
Hello,

I found out that when I submitted the module it didn't add the new code and instead an older version. I just submitted the new one 1.3.3.
I will let it know as soon as it is available.

**Comment by dr01d3r** [comment]
Great, thank you.

**Comment by knil-maloon** [comment]
Version 1.3.3 it's already available
