### ISSUE TITLE
Preload email addresses functionality broken on 1.3.3

### ISSUE THREAD

**Issue by eaneuhaus** [vanderbilt-redcap/email-alerts-module#6]
No email addresses seem to be found when attempting to autocomplete with the "Preload email addresses" setting configured. This issue is on v1.3.3.

When I rollback to v1.2, it works as expected.

**Comment by knil-maloon** [comment]
Thanks @eaneuhaus I will check it out.

**Comment by knil-maloon** [comment]
Fixed in v1.3.4.
