### ISSUE TITLE
Deletion status tied to alert indexes?

### ISSUE THREAD

**Issue by eaneuhaus** [vanderbilt-redcap/email-alerts-module#7]
While testing this module, I noticed that at some point, new alerts I create would immediately be "deleted" and not appear in the list of enabled alerts. After testing some more, my understanding is that the indexes of the alerts ("Alert #0") are what is marked as "deleted" as opposed to the actual alert instance, which can create some confusion if alerts are permanently deleted and the indexes are shifted.

I think it would be ideal if deletion status was tied to specific alert instances instead of indexes...or if permanently deleted indexes were just gone forever and alerts added in the future just continued to increment from the total.

This is likely a minor issue for most (I can't imagine alerts are being permanently deleted very often), but it can be very confusing when it happens.

**Comment by knil-maloon** [comment]
Thank you for your suggestion, we will take it under consideration for future updates.

**Comment by knil-maloon** [comment]
New version 2.0 solves this
