### ISSUE TITLE
"Enable Data Piping to email addresses" in fields other than To/From/BCC

### ISSUE THREAD

**Issue by eaneuhaus** [vanderbilt-redcap/email-alerts-module#8]
Pressing the blue labeled button generated from the "Enable Data Piping to email addresses" when creating an alert generates the related variable to be piped. It looks like this is intended for the To/From/BCC fields, which works as expected, but it's also possible to pipe it into any other field when creating an alert (like Subject/Message). However, the value will not pipe properly in the email content (instead just showing [email] or something similar).

This seems like a minor oversight and I can't imagine there are many use cases for piping email addresses into email Subjects/Messages, but it may be confusing for some users and might be worth allowing this piping to happen or limiting what fields the button can be used with (moving the button may also help, since it's currently right above the message box and it seems as though it should work like the other buttons).

**Comment by knil-maloon** [comment]
Thank you for your suggestion, we will take it under consideration for future updates.

**Comment by knil-maloon** [comment]
Enabled data pipping to email addresses limited to the field type on version 1.3.6
