### ISSUE TITLE
Redcap variables in attachment leads to random attachments of other projects

### ISSUE THREAD

**Issue by mikestoller** [vanderbilt-redcap/email-alerts-module#9]
REDCap 8.1.8 LTS.
Redcap variables in attachment lead to Email Alert containing random attachments of other projects, e.g. pdfs and reports of other projects.

**Comment by knil-maloon** [comment]
Hi @mikestoller is the project repeatable? If so the event needs to be specified as well as the variable name. As for other projects, do you mean instruments? Email alerts is activated by project so it sounds very weird for it going to other projects. Other instruments is normal as long as the variable name is the same.
You can also you can check in the "Logging" section which alerts were activated on which records and the email that was sent. That might be helpful to see what might be going on.

**Comment by mikestoller** [comment]
@knil-maloon the project is non-repeatable and non-longitudinal. However, the error might also be due to an incomplete "dump" on the test version of redcap where I tested the module.

**Comment by knil-maloon** [comment]
@mikestoller I just made a test of an attached variable in the test server and it send me the email with the attached file I uploaded

**Comment by mikestoller** [comment]
@knil-maloon  Thank you. To clarify: I put variables into the attachment, which were not of field type "file upload". I then got the random attachments.

**Comment by knil-maloon** [comment]
Oh! Well the variable attachment only work for file types if you try to attach something that is not a document but a normal variable I guess it's normal it does crazy things haha.

**Comment by mikestoller** [comment]
@knil-maloon  ah, I see xD Well, the problem is that this way people can get confidential data from other projects, so you might still want to consider to address it ;)

**Comment by knil-maloon** [comment]
Yeah, it's a good point.
Thank you for your suggestion, we will take it under consideration for future updates.

**Comment by knil-maloon** [comment]
Fixed on version 1.3.7
